apiVersion: v1
kind: Pod
metadata:
  name: cpu-test
  labels:
    workload-type: cpu
    experiment: scheduler-eval
spec:
  containers:
    - name: cpu-stress
      image: polinux/stress
      command: ["stress"]
      args: ["--cpu", "1", "--timeout", "60"]
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
  restartPolicy: Never
