apiVersion: v1
kind: Pod
metadata:
  name: mem-lite-test
  labels:
    workload-type: memory-lite
    experiment: scheduler-eval
spec:
  containers:
    - name: mem-lite-stress
      image: polinux/stress
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "96M", "--timeout", "45"]
      resources:
        requests:
          cpu: "75m"
          memory: "96Mi"
        limits:
          cpu: "150m"
          memory: "192Mi"
  restartPolicy: Never