apiVersion: v1
kind: Pod
metadata:
  name: mem-test
  labels:
    workload-type: memory
    experiment: scheduler-eval
spec:
  containers:
    - name: mem-stress
      image: polinux/stress
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "256M", "--timeout", "60"]
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "512Mi"
  restartPolicy: Never
